Update coverage invocation
funcx-faas/funcx-common pull request #51
Opened 2022-07-14 18:46 UTC by khk-globus

2022-07-14 19:04 UTC, sirosen requested changes
This PR does not describe itself accurately. It has numerous effects other than a simple switch from `pytest-cov` to `coverage`.

If `pytest-cov` is being removed -- which would be fine -- then the installable extras need to be updated in `setup.cfg`:
https://github.com/funcx-faas/funcx-common/blob/d3841ac364e6774cc5fc5d413a0337c171e6588b/setup.cfg#L35

2022-07-14 19:04 UTC, sirosen commented on tox.ini
> +envlist = py{37,38,39,310}
The `-nodeps` builds guard against introduction of hard dependencies on third party libraries.

That makes it safer and easier to maintain a library which _allows_ integration with `redis`, `boto3`, and potentially other libraries, but doesn't require them to be present in order to be importable.

Removing this testing may impact the safety of relying on `funcx-common` in client-side software like `funcx` and `funcx-endpoint`, so I would recommend very strongly against doing this.

2022-07-14 19:04 UTC, sirosen commented on tox.ini
> +    coverage
Removing the `!nodeps` factorized installation of `boto3` and `moto` means that tests requiring boto3+moto will never run.

2022-07-15 01:40 UTC, khk-globus commented
Temporarily closing until I get back to this.

2022-07-15 01:40 UTC, closed without merging